---
title: "R Wildlife Study Group Code"
output: html_document
---

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(shiny)
library(maps)
library(RColorBrewer)
library(scatterpie)
library(treemap)
library(ggthemes)
```

```{r}
#Data loading and cleaning
WildlifeStudy <- read.csv("data/FelidaeDataSTA223.csv")
#str(WildlifeStudy)
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "\\(.*$","")

WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "[']","")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "\\-.*", "")
```

```{r}
#Animal Grouping
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Dark", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Spotted Towhee", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "pigeion", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Scrub Jay", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "American Robin", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Mourning Dove", "Bird")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Stellers Jay", "Bird")

WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Eastern Grey Squirrel", "Squirrel")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Western Gray Squirrel", "Squirrel")


WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Sonoma Chipmunk", "Chipmunk")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Merriams Chipmunk", "Chipmunk")


WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Jackrabbit", "Rabbit")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Desert Cottontail", "Rabbit")
WildlifeStudy$Common <- str_replace_all(WildlifeStudy$Common, "Brush Rabbit", "Rabbit")
```

```{r}
#Creating Niches
WildlifeStudy$Niche[WildlifeStudy$Common == "Cattle"] <- "Domestic"
WildlifeStudy$Niche[WildlifeStudy$Common == "Dog"] <- "Domestic"
WildlifeStudy$Niche[WildlifeStudy$Common == "Horse"] <- "Domestic"

WildlifeStudy$Niche[WildlifeStudy$Common == "HWHR"] <- "Human"
WildlifeStudy$Niche[WildlifeStudy$Common == "HO"] <- "Human"
WildlifeStudy$Niche[WildlifeStudy$Common == "HD"] <- "Human"
WildlifeStudy$Niche[WildlifeStudy$Common == "HB"] <- "Human"
WildlifeStudy$Niche[WildlifeStudy$Common == "HH"] <- "Human"

WildlifeStudy$Niche[WildlifeStudy$Common == "Bobcat"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "Coyote"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "Owl"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "Burrowing Owl"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "American Badger"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "American Black Bear"] <- "Predator"
WildlifeStudy$Niche[WildlifeStudy$Common == "Puma"] <- "Predator"

WildlifeStudy$Niche[WildlifeStudy$Common == "Common Raven"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "American Crow"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Opossum"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Striped Skunk"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Spotted Skunk"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Raccoon"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Rat "] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Wild Pig"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Grey Fox"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Red Fox"] <- "Mesocarnivore"
WildlifeStudy$Niche[WildlifeStudy$Common == "Bat "] <- "Mesocarnivore"

WildlifeStudy$Niche[WildlifeStudy$Common == "Bird"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Deer"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Porcupine "] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Rabbit"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Mouse"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Squirrel"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Chipmunk"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "California Quail"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Unknown species"] <- "Prey"
WildlifeStudy$Niche[WildlifeStudy$Common == "Turkey"] <- "Prey"

```

```{r}
#Designating Study Years
WildlifeStudy$date2 <-WildlifeStudy$Date
WildlifeStudy <- separate(data = WildlifeStudy, col = date2, into = c("Month", "Year"), sep = "/.*/")
WildlifeStudy$date2 <- str_replace_all(WildlifeStudy$Date, "/.*/", "-")

WildlifeStudy$Month[WildlifeStudy$Month == "1"] <- "01"
WildlifeStudy$Month[WildlifeStudy$Month == "2"] <- "02"
WildlifeStudy$Month[WildlifeStudy$Month == "3"] <- "03"
WildlifeStudy$Month[WildlifeStudy$Month == "4"] <- "04"
WildlifeStudy$Month[WildlifeStudy$Month == "5"] <- "05"
WildlifeStudy$Month[WildlifeStudy$Month == "6"] <- "06"
WildlifeStudy$Month[WildlifeStudy$Month == "7"] <- "07"
WildlifeStudy$Month[WildlifeStudy$Month == "8"] <- "08"
WildlifeStudy$Month[WildlifeStudy$Month == "9"] <- "09"

WildlifeStudy$date3 <- paste(WildlifeStudy$Year,WildlifeStudy$Month,sep="-")

WildlifeStudy$StudyYear[WildlifeStudy$date2 == "9-2017"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "10-2017"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "11-2017"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "12-2017"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "1-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "2-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "3-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "4-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "5-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "6-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "7-2018"] <-  "1"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "8-2018"] <-  "1"

WildlifeStudy$StudyYear[WildlifeStudy$date2 == "9-2018"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "10-2018"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "11-2018"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "12-2018"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "1-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "2-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "3-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "4-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "5-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "6-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "7-2019"] <-  "2"
WildlifeStudy$StudyYear[WildlifeStudy$date2 == "8-2019"] <-  "2"


```

```{r}
#the camera Numbers: Jenner: JNR02A, JNR04A, JNR08B, JNR12A, JNR13A, JNR14B, JNR18A, JNR19A  Pol: POL01A, POL02B LMB: LBM01A, LBM02B
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR02A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR08B"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR04A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR12A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR13A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR14B"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR18A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "JNR19A"] <- "Jenner"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "POL01A"] <- "Pole"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "POL02B"] <- "Pole"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "LBM01A"] <- "LBM"
WildlifeStudy$Area[WildlifeStudy$CamNumber1 == "LBM02B"] <- "LBM"
```

```{r}
#Coordinates
WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR02A"] <- -123.072189
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR02A"] <- 38.482444

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR04A"] <- -123.1073588
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR04A"] <- 38.4788876

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR08B"] <- -123.070454
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR08B"] <- 38.473451

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR12A"] <- -123.123516
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR12A"] <- 38.493872

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR13A"] <- -123.150569
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR13A"] <- 38.475672

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR14B"] <- -123.0951853
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR14B"] <- 38.4800865

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR18A"] <- -123.129404
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR18A"] <- 38.484848

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "JNR19A"] <- -123.117577
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "JNR19A"] <- 38.472775

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "POL01A"] <- -123.119419
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "POL01A"] <- 38.504947

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "POL02B"] <- -123.130420
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "POL02B"] <- 38.507285

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "LBM01A"] <- -123.119434
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "LBM01A"] <- 38.509953

WildlifeStudy$Longitude[WildlifeStudy$CamNumber1 == "LBM02B"] <- -123.125492
WildlifeStudy$Latitude[WildlifeStudy$CamNumber1 == "LBM02B"] <- 38.509049
```

```{r}
#Data Subsetting
JennerSubset <- subset(WildlifeStudy, Area == "Jenner")
PoleSubset <- subset(WildlifeStudy, Area == "Pole")
LBMSubset <- subset(WildlifeStudy, Area == "LBM")
```

```{r}
#Bargraphs
ggplot(data = LBMSubset) + geom_bar(mapping = aes(x = date3, fill = Niche)) + labs(title = "Little Black Mtn Niches", y = "Number of Detections", x = "Date") +theme(axis.text.x = element_text(angle = 90)) + geom_vline(xintercept = 13.5, color = "black")

ggplot(data = PoleSubset) + geom_bar(mapping = aes(x = date3, fill = Niche)) + labs(title = "Pole Mtn Niches", y = "Number of Detections", x = "Date") +theme(axis.text.x = element_text(angle = 90)) +geom_vline(xintercept = 16.5, color = "black")

ggplot(data = JennerSubset) + geom_bar(mapping = aes(x = date3, fill = Niche)) + labs(title = "Jenner Niches", y = "Number of Detections", x = "Date") +theme(axis.text.x = element_text(angle = 90))+geom_vline(xintercept = 16.5, color = "black")
```


```{r}
# #Make function for niche count
# CountNicheFreqWS <- function(WildlifeStudy, InputNiche){
#   a <- WildlifeStudy %>% group_by(WildlifeStudy$date3, WildlifeStudy$Area) 
#   c <- sum(a$Indiv.[a$Niche == InputNiche],na.rm = TRUE)
# d <- (summarise(a,sum=sum(Indiv.[a$Niche == InputNiche],na.rm= TRUE)))
#   return(d)}
# 
# CountNicheFreqWS(WildlifeStudy,"Predator")

#Make function for niche count
CountCamFreq <- function(WildlifeStudy, InputNiche){
  a <- WildlifeStudy %>% group_by(WildlifeStudy$date3, WildlifeStudy$CamNumber1) 
  c <- sum(a$Indiv.[a$Niche == InputNiche],na.rm = TRUE)
d <- (summarise(a,sum=sum(Indiv.[a$Niche == InputNiche],na.rm= TRUE)))
  return(d)}

PredatorCam <- CountCamFreq(WildlifeStudy, "Predator")
names(PredatorCam)[1] <- "Date3" 
names(PredatorCam)[2] <- "Camera" 
names(PredatorCam)[3] <- "PredatorSum" 

PreyCam <- CountCamFreq(WildlifeStudy, "Prey")
names(PreyCam)[1] <- "Date3" 
names(PreyCam)[2] <- "Camera" 
names(PreyCam)[3] <- "PreySum" 

MesoCam <- CountCamFreq(WildlifeStudy, "Mesocarnivore")
names(MesoCam)[1] <- "Date3" 
names(MesoCam)[2] <- "Camera" 
names(MesoCam)[3] <- "MesoSum" 

HumanCam <- CountCamFreq(WildlifeStudy, "Human")
names(HumanCam)[1] <- "Date3" 
names(HumanCam)[2] <- "Camera" 
names(HumanCam)[3] <- "HumanSum" 

DomesticCam <- CountCamFreq(WildlifeStudy, "Domestic")
names(DomesticCam)[1] <- "Date3" 
names(DomesticCam)[2] <- "Camera" 
names(DomesticCam)[3] <- "DomesticSum" 


CamSum <- inner_join(x = DomesticCam, y = HumanCam, by = c("Date3","Camera"))
CamSum <- inner_join(x = CamSum, y = MesoCam, by = c("Date3","Camera"))
CamSum <- inner_join(x = CamSum, y = PreyCam, by = c("Date3","Camera"))
CamSum <- inner_join(x = CamSum, y = PredatorCam, by = c("Date3","Camera"))
```

```{r}
#CamSum Cordinates
CamSum$Longitude[CamSum$Camera == "JNR02A"] <- -123.072189
CamSum$Latitude[CamSum$Camera == "JNR02A"] <- 38.482444

CamSum$Longitude[CamSum$Camera == "JNR04A"] <- -123.1073588
CamSum$Latitude[CamSum$Camera == "JNR04A"] <- 38.4788876

CamSum$Longitude[CamSum$Camera == "JNR08B"] <- -123.070454
CamSum$Latitude[CamSum$Camera == "JNR08B"] <- 38.473451

CamSum$Longitude[CamSum$Camera == "JNR12A"] <- -123.123516
CamSum$Latitude[CamSum$Camera == "JNR12A"] <- 38.493872

CamSum$Longitude[CamSum$Camera == "JNR13A"] <- -123.150569
CamSum$Latitude[CamSum$Camera == "JNR13A"] <- 38.475672

CamSum$Longitude[CamSum$Camera == "JNR14B"] <- -123.0951853
CamSum$Latitude[CamSum$Camera == "JNR14B"] <- 38.4800865

CamSum$Longitude[CamSum$Camera == "JNR18A"] <- -123.129404
CamSum$Latitude[CamSum$Camera == "JNR18A"] <- 38.484848

CamSum$Longitude[CamSum$Camera == "JNR19A"] <- -123.117577
CamSum$Latitude[CamSum$Camera == "JNR19A"] <- 38.472775

CamSum$Longitude[CamSum$Camera == "POL01A"] <- -123.119419
CamSum$Latitude[CamSum$Camera == "POL01A"] <- 38.504947

CamSum$Longitude[CamSum$Camera == "POL02B"] <- -123.130420
CamSum$Latitude[CamSum$Camera == "POL02B"] <- 38.507285
#bumped up Latitude of both LBM by 0.002
CamSum$Longitude[CamSum$Camera == "LBM01A"] <- -123.119434
CamSum$Latitude[CamSum$Camera == "LBM01A"] <- 38.511953

CamSum$Longitude[CamSum$Camera == "LBM02B"] <- -123.125492
CamSum$Latitude[CamSum$Camera == "LBM02B"] <- 38.511049
```
```{r}
#Adding total column
CamSum <- mutate(CamSum, TotalSum = DomesticSum + HumanSum + MesoSum + PreySum + PredatorSum)
```

